[Definition]
failregex = ^<HOST>.*"GET .*HTTP.*" (403|404) \d+
            ^<HOST>.*"(HEAD|OPTIONS) \/.*HTTP.* 
            ^<HOST>.*"\/\.git\/.* 
            ^<HOST>.*"\/\.env.*
            ^<HOST>.*"\/wp-includes.*
ignoreregex =