[Definition]
actionstart = touch /etc/nginx/conf.d/banned/banned_ips.conf
              chmod 644 /etc/nginx/conf.d/banned/banned_ips.conf
actionstop = rm -f /etc/nginx/conf.d/banned/banned_ips.conf
actioncheck = test -f /etc/nginx/conf.d/banned/banned_ips.conf
actionban = echo "deny <ip>;" >> /etc/nginx/conf.d/banned/banned_ips.conf
           nginx -s reload
actionunban = sed -i '/deny <ip>;/d' /etc/nginx/conf.d/banned/banned_ips.conf
             nginx -s reload
[Init]