server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    
    # Self-signed certificate
    ssl_certificate /var/proxma/ssl/default.crt;
    ssl_certificate_key /var/proxma/ssl/default.key;
    
    # Prevent browsers from automatically redirecting to HTTPS
    add_header Strict-Transport-Security "max-age=0" always;
    
    # Explicitly tell browsers not to upgrade to HTTPS
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    
    server_name _;
    root /var/www/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}