events {}
http {
    include mime.types;
    default_type application/octet-stream;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    sendfile on;
    keepalive_timeout 65;

    # include explicitly preserved default configuration files 
    include /etc/nginx/default_available/*.conf;

    # regular proxma-generated configurations
    include /etc/nginx/conf.d/*.conf;
}